apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tenable-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tenable-exporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tenable-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tenable-exporter.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tenable-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TENABLE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "tenable-exporter.secretName" . }}
                  key: access-key
            - name: TENABLE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "tenable-exporter.secretName" . }}
                  key: secret-key
            - name: EXPORTER_PORT
              value: "9190"
            - name: SCRAPE_INTERVAL
              value: {{ .Values.tenable.scrapeInterval | quote }}
            {{- if .Values.tenable.filterProviders }}
            - name: TENABLE_FILTER_PROVIDERS
              value: {{ .Values.tenable.filterProviders | quote }}
            {{- end }}
            {{- if .Values.tenable.filterSubscriptions }}
            - name: TENABLE_FILTER_SUBSCRIPTIONS
              value: {{ .Values.tenable.filterSubscriptions | quote }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 9190
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
