{{- if and (not .Values.tenable.existingSecret) (not .Values.tenable.accessKey) }}
{{- fail "Either tenable.accessKey (+ tenable.secretKey) or tenable.existingSecret must be set" }}
{{- end }}
{{- if and (not .Values.tenable.existingSecret) .Values.tenable.accessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tenable-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tenable-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.tenable.accessKey | quote }}
  secret-key: {{ .Values.tenable.secretKey | quote }}
{{- end }}
